version: "3"
services:
  web:
    build:
      context: .
      dockerfile: webserver.Dockerfile
    environment:
      - DBSRVNAME=distributedhttpserver_db_
      - DBSRVPORT=:8081
      - DBSRVS=1
      - LOGSRV=distributedhttpserver_log_1:8082
    depends_on:
      - log
      - db
    ports:
      - "8080:8080"
    networks:
      - backend

  log:
    build:
      context: .
      dockerfile: logserver.Dockerfile
    environment:
      - LOGFILE=log.txt
    networks:
      - backend

  db:
    build:
      context: .
      dockerfile: dbserver.Dockerfile
    networks:
      - backend

networks:
  backend: