version: "3"
services:
  web:
    build:
      context: .
      dockerfile: webServerDockerfile
    environment:
      - DBSRVNAME=distributedhttpserver_db_
      - DBSRVPORT=:8081
      - DBSRVS=2
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - backend

  db:
    build:
      context: .
      dockerfile: dbServerDockerfile
    networks:
      - backend

networks:
  backend: