version: "3"
services:
  web:
    build:
      context: .
      dockerfile: webServerDockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - backend

  db:
    build:
      context: .
      dockerfile: dbServerDockerfile
    networks:
      - backend

networks:
  backend: